### ISSUE TITLE
Missing input [plant] in branches

### ISSUE THREAD

**Issue by avaer** [jim-fx/plantarium#87] opened 2022-05-24 14:53 UTC
I am using https://plant.jim-fx.com/

As far as I can tell, this layout is ok, but the editor is complaining about errors I don't know how to fix. It looks like everything is connected. Is this a bug?

![image](https://user-images.githubusercontent.com/6926057/170065875-b4d1750b-7314-4969-9f3e-837db642a16d.png)

**Comment by avaer** [comment] 2022-05-24 14:55
Simplifying, it still doesn't work:
![image](https://user-images.githubusercontent.com/6926057/170066523-e87efe83-5974-4139-8430-973c41df02c8.png)

**Comment by jim-fx** [comment] 2022-05-24 21:46
Thank you for the report! Yeah, internally there is some duplication in the management of connection of nodes. I definitely need to refactor that...

Normally, reloading the page updates the nonexisting connections to disappear, but that can't be the way it works.

I will invest some time maybe tomorrow to dig deeper into this problem!

Cheers, Jim :)

**Comment by jim-fx** [comment] 2022-05-25 17:42
Okay, removed the duplicated code, but I will leave the issue open for some time if any new issues appear

**Comment by jim-fx** [comment] 2022-05-26 17:05
After some testing, I could not reproduce it with the current version, closing.

**Closed by jim-fx** 2022-05-26 17:05 UTC
Labels: bug, P:NodeSystem
